version: 2
jobs:
  build:
      working_directory: ~/restapi
      docker:
        - image: circleci/python:3.6.4
          environment:
            PIPENV_VENV_IN_PROJECT: true
        - image: circleci/postgres:9.6.2
          environment:
            POSTGRES_USER: root
            POSTGRES_DB: circle_test
      steps:
        - checkout
        - run: sudo chown -R circleci:circleci /usr/local/bin
        - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
        - restore_cache:
            key: deps-{{ checksum "Pipfile.lock" }}
        - run:
            name: Install pipenv
            command: sudo pip install pipenv
        - run:
            name: Install dependencies
            command: pipenv install
        - save_cache:
            key: deps-{{ checksum "Pipfile.lock" }}
            paths:
              - ".venv"
              - "/usr/local/bin"
              - "/usr/local/lib/python3.6/site-packages"
        - run:
            name: test
            command: pipenv run "python manage.py test"
        - store_test_results:
            path: test-results