version: 2
jobs:
  build:
      working_directory: ~/restapi
      docker:
        - image: circleci/python:3.6.4
          environment:
            PIPENV_VENV_IN_PROJECT: true
      steps:
        - checkout
        - run: sudo chown -R circleci:circleci /usr/local/bin
        - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
        - restore_cache:
            key: deps-{{ checksum "Pipfile.lock" }}
        - run:
            name: Install pipenv
            command: sudo pip install pipenv
        - run:
            name: Install dependencies
            command: pipenv install
        - save_cache:
            key: deps-{{ checksum "Pipfile.lock" }}
            paths:
              - ".venv"
              - "/usr/local/bin"
              - "/usr/local/lib/python3.6/site-packages"
        - run:
            name: test
            command: pipenv run "python manage.py test"
        - store_test_results:
            path: test-results
    deploy:
        working_directory: ~/restapi
        machine:
            enabled: true
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "b9:24:92:ed:aa:09:92:61:4e:ec:99:c5:a4:45:ff:ca"
            - run:
                name: Setup heroku
                command: bash .circleci/setup-heroku.sh
            - run:
                name: Add heroku remote
                command: heroku git:remote -a ucll-cc-restapi
            - run:
                name: Push it to heroku
                command: git push --force git@heroku.com:ucll-cc-restapi.git HEAD:refs/heads/master
            - run:
                name: Run the migrations
                command: heroku run python manage.py migrate

workflows:
  version: 2
  test-deploy:
    jobs:
      - build
      - deploy:
          requires:
              - build

